#!/usr/bin/env python3
"""memory-os execution heartbeat.

Registration is not execution: a cron job can be registered and still never
run (observed in production 2026-07-20 — both loops silently dead for 2 days
while verify_cron reported VERIFIED). This script checks the artifacts the
loops actually PRODUCE:

  - daily MINE       -> newest memory/inbox/*-mined*.md date
  - consolidation    -> newest "## YYYY-MM-DD" consolidation-class heading in
                        memory/log.md or memory/changelog.md

Exit 0 = all loops fresh. Exit 1 = at least one loop overdue (stale memory).
Also maintains a marker-delimited HEARTBEAT block in memory/health.md so the
status is visible to every session that reads health.

Usage:
  python3 heartbeat.py [--root=PATH] [--init]
    --init   stamp a baseline without failing (first run after SETUP)
Env: MEMORY_ROOT overrides root resolution. Root default: script-relative.
Thresholds: mine overdue after >3 calendar days (weekend-tolerant);
consolidation overdue after >8 days.

Backfill gate (fixed 2026-07-21): a fresh vault has nothing to consolidate yet,
so the consolidation clock does NOT start until the 90-day backfill has landed.
While any inbox mine file still carries `backfill_pending: true`, consolidation
is reported "awaiting backfill — not yet due" and never OVERDUE. This kills the
false "memory is going stale" alarm participants otherwise hit on their 2nd
session (a 1-day-old vault). Grounded in the same evidence→claim discipline as
the rest of memory-os: don't assert staleness before there is anything to stale.
"""
import os, re, sys, datetime

def _resolve_root():
    if os.environ.get("MEMORY_ROOT"):
        return os.environ["MEMORY_ROOT"]
    for arg in sys.argv[1:]:
        if arg.startswith("--root="):
            return arg.split("=", 1)[1]
    return os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

ROOT = _resolve_root()
TODAY = datetime.date.today()
MINE_MAX_DAYS = 3
CONSOL_MAX_DAYS = 8
BEGIN = "<!-- HEARTBEAT:BEGIN (generated by scripts/heartbeat.py — do not hand-edit) -->"
END = "<!-- HEARTBEAT:END -->"

DATE_RE = re.compile(r"(\d{4}-\d{2}-\d{2})")


def last_mine_date():
    inbox = os.path.join(ROOT, "inbox")
    if not os.path.isdir(inbox):
        return None
    dates = []
    for fn in os.listdir(inbox):
        if "mined" in fn and fn.endswith(".md"):
            m = DATE_RE.search(fn)
            if m:
                try:
                    dates.append(datetime.date.fromisoformat(m.group(1)))
                except ValueError:
                    pass
    return max(dates) if dates else None


def last_consolidation_date():
    dates = []
    for name in ("log.md", "changelog.md"):
        p = os.path.join(ROOT, name)
        if not os.path.isfile(p):
            continue
        text = open(p, encoding="utf-8").read()
        # date-headed sections whose heading line mentions consolidation
        for m in re.finditer(r"^##+ .*?(\d{4}-\d{2}-\d{2}).*$", text, re.M):
            line = m.group(0).lower()
            if "consolidat" in line or "weekly" in line:
                try:
                    dates.append(datetime.date.fromisoformat(m.group(1)))
                except ValueError:
                    pass
    return max(dates) if dates else None


def backfill_state():
    """Return ('landed', date) | ('pending', None) | ('none', None).

    Decided by the NEWEST mine file's flag, not by "any non-pending file exists".
    That earlier heuristic was wrong: a normal daily mine that happened to run
    before the deferred backfill would falsely read 'landed'. The backfill is
    what clears `backfill_pending` (or writes a newer unflagged mine file), so
    the newest mine file's flag is the authoritative signal.

    'landed'  = newest mine file has no `backfill_pending: true` → backfill ran;
                consolidation clock starts from that file's date.
    'pending' = newest mine file still carries the flag → not yet landed;
                consolidation is not yet due.
    'none'    = no mine has ever run.
    """
    inbox = os.path.join(ROOT, "inbox")
    if not os.path.isdir(inbox):
        return ("none", None)
    files = []  # (date_or_min, filename)
    for fn in os.listdir(inbox):
        if "mined" not in fn or not fn.endswith(".md"):
            continue
        m = DATE_RE.search(fn)
        try:
            fdate = datetime.date.fromisoformat(m.group(1)) if m else datetime.date.min
        except ValueError:
            fdate = datetime.date.min
        files.append((fdate, fn))
    if not files:
        return ("none", None)
    fdate, fn = max(files)  # newest by embedded date
    head = open(os.path.join(inbox, fn), encoding="utf-8").read()[:600]
    if re.search(r"^backfill_pending:\s*true\b", head, re.M):
        return ("pending", None)
    return ("landed", fdate if fdate != datetime.date.min else TODAY)


def consolidation_line(consol):
    """Gate consolidation-overdue on the backfill having landed."""
    if consol is not None:
        return _fmt(consol, CONSOL_MAX_DAYS, "Last consolidation")
    state, landed = backfill_state()
    if state != "landed":
        why = "awaiting 90-day backfill" if state == "pending" else "no mine yet"
        return (f"- Last consolidation: not yet due ({why}) ✓", False)
    age = (TODAY - landed).days
    overdue = age > CONSOL_MAX_DAYS
    flag = " ⚠️ OVERDUE" if overdue else " ✓ (not yet due)"
    return (f"- Last consolidation: none yet; backfill landed {landed} "
            f"({age}d ago; due after {CONSOL_MAX_DAYS}d){flag}", overdue)


def _fmt(d, max_days, label):
    if d is None:
        return (f"- {label}: **never recorded** ⚠️", True)
    age = (TODAY - d).days
    overdue = age > max_days
    flag = " ⚠️ OVERDUE" if overdue else " ✓"
    return (f"- {label}: {d} ({age}d ago; threshold {max_days}d){flag}", overdue)


def update_health_block(lines):
    p = os.path.join(ROOT, "health.md")
    block = "\n".join([BEGIN, "## Heartbeat (loop execution — checked, not promised)", ""] + lines + ["", f"_Last heartbeat run: {TODAY}_", END])
    if os.path.isfile(p):
        text = open(p, encoding="utf-8").read()
        if BEGIN in text and END in text:
            text = re.sub(re.escape(BEGIN) + r".*?" + re.escape(END), block, text, flags=re.S)
        else:
            text = text.rstrip() + "\n\n" + block + "\n"
    else:
        text = "# Memory Health\n\n" + block + "\n"
    open(p, "w", encoding="utf-8").write(text)


def main():
    init = "--init" in sys.argv
    mine = last_mine_date()
    consol = last_consolidation_date()
    l1, o1 = _fmt(mine, MINE_MAX_DAYS, "Last daily MINE")
    l2, o2 = consolidation_line(consol)
    any_overdue = (o1 or o2) and not init
    status = "OVERDUE — memory is going stale; run the missed loop" if any_overdue else ("BASELINE STAMPED" if init else "HEALTHY")
    lines = [f"**Status: {status}**", "", l1, l2]
    update_health_block(lines)
    print("\n".join(lines))
    sys.exit(1 if any_overdue else 0)


if __name__ == "__main__":
    main()
